import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Script from "next/script";
import Buybutton from "../components/buybutton";

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Buybutton />

      <footer className=''></footer>
    </div>
  );
}
